# Generated by Django 4.0.3 on 2022-03-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('Id', models.AutoField(max_length=40, primary_key=True, serialize=False)),
                ('firstname', models.CharField(default='', max_length=50)),
                ('lastname', models.CharField(default='', max_length=50)),
                ('dateOfBirth', models.DateField(default='', max_length=50)),
                ('Email', models.CharField(default='', max_length=50)),
                ('phone', models.IntegerField(default='', max_length=50)),
                ('country', models.CharField(default='', max_length=50)),
                ('state', models.CharField(default='', max_length=50)),
                ('area', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=50)),
                ('pincode', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
