# Generated by Django 4.0.3 on 2022-03-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstComponent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='Id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='register',
            name='phone',
            field=models.IntegerField(default=''),
        ),
    ]
